### ISSUE TITLE
LiT integration: bake and use super macaroon

### ISSUE THREAD

**Issue by guggero** [lightninglabs/lightning-node-connect#17]
Depends on https://github.com/lightninglabs/lightning-terminal/pull/278.

Currently LiT uses the UI password in the `authData` payload of the noise handshake because there is no single macaroon that can be used for all calls (to lnd/loop/pool/faraday).
With the possibility of baking and verifying a super macaroon in LiT we can instead use that super macaroon directly instead of the UI password that gets converted into the correct daemon specific macaroon on the LiT proxy side.

**Comment by ellemouton** [comment]
anything left to do for this issue @guggero ?
