### ISSUE TITLE
Connectivity problems after v0.1.6 update

### ISSUE THREAD

**Issue by jamaljsr** [lightninglabs/lightning-node-connect#29]
After updating Terminal Web staging to use LNC v0.1.6, i've noticed that I was unable to connect to my testnet (running [PR 315](https://github.com/lightninglabs/lightning-terminal/pull/315)) & mainnet ([v0.6.1](https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.6.1-alpha))  litd nodes any longer. Even after obtaining a new pairing phrase. The issue was resolved by restarting litd in both cases. Unfortunately, I dont have logs to share. I've been trying to reproduce the problem with no luck so far. I just wanted to make a note of the issue. My concern is that we deploy LNC v0.1.6 to prod, then all users need to obtain a new pairing phrase or restart `litd` in order to reconnect to Terminal Web.

**Comment by levmi** [comment]
I had a similar issue. I haven't re-started litd so that I could repro. Dropping the logs from my issue here.
<img width="559" alt="Screen Shot 2022-01-24 at 10 56 03 AM" src="https://user-images.githubusercontent.com/87084908/150846439-1dff972a-dc0c-42e7-8032-207f8af5388f.png">

**Comment by guggero** [comment]
Hmm, not sure why that would happen. Could be because we deployed aperture? We probably need to look into that to make sure a deployment on our end doesn't make a restart mandatory.

I think once we also deploy the server-side fix (https://github.com/lightninglabs/lightning-terminal/pull/315), things should get more stable.

**Comment by ellemouton** [comment]
Can we close this @jamaljsr ?

**Comment by jamaljsr** [comment]
Yes, i think its safe to close this now. This hasn't been a ongoing issue.
