### ISSUE TITLE
Cannot reconnect after disconnect

### ISSUE THREAD

**Issue by jamaljsr** [lightninglabs/lightning-node-connect#46]
After connecting to a session, then disconnecting using `wasmClientDisconnect`, you must reload the web page in order to connect again. If I call `wasmClientConnectServer` without reloading the page, nothing happens.

This was feedback we got from the Alby team in their testing of `lnc-web`.

**Comment by ellemouton** [comment]
cool, thanks for opening the issue. This is definitely something we can fix 👍
